import type { AppLanguage } from './types';

export type LegalSection = { title: string; text: string };

export const legalSections: Record<AppLanguage, LegalSection[]> = {
  'pt-BR': [
    { title: '1. Uso do Raddo', text: 'O Raddo é um app social para conhecer pessoas próximas, conversar em matches e participar de chats locais no mapa. Ao usar o app, você concorda em respeitar outros usuários e não publicar conteúdo ilegal, ofensivo, sexual envolvendo menores, violento, fraudulento, discriminatório ou que viole direitos de terceiros.' },
    { title: '2. Idade mínima', text: 'O Raddo é destinado apenas a pessoas com 18 anos ou mais. Contas suspeitas de pertencer a menores de idade podem ser removidas ou banidas sem aviso prévio.' },
    { title: '3. Localização', text: 'O app usa sua localização para calcular distâncias, mostrar chats próximos e melhorar a descoberta de pessoas no seu alcance. Sua foto só aparece no mapa quando você ativa essa opção, que pode ser desativada nas configurações de segurança.' },
    { title: '4. Perfil, fotos e mensagens', text: 'Você é responsável pelas informações, fotos, mensagens e chats que publica. Fotos de perfil, capas de chats e imagens enviadas podem passar por verificação automática e revisão humana quando necessário para proteger a comunidade.' },
    { title: '5. Conteúdo proibido', text: 'É proibido publicar nudez explícita, exploração sexual, conteúdo envolvendo menores, assédio, ameaças, discurso de ódio, golpes, spam, divulgação indevida de dados pessoais, violência extrema ou qualquer material ilegal.' },
    { title: '6. Denúncias, bloqueios e moderação', text: 'Usuários podem denunciar perfis, chats e conteúdos inadequados. O Raddo pode analisar denúncias, remover conteúdo, limitar recursos, bloquear chats ou banir contas. Donos e moderadores de chats também podem remover mensagens e participantes.' },
    { title: '7. Privacidade e dados', text: 'Coletamos dados necessários ao funcionamento, como perfil, fotos, preferências, localização quando ativada, curtidas, matches, mensagens, denúncias, bloqueios, tokens de notificação e registros técnicos. Eles são usados para autenticação, descoberta, chat, segurança e prevenção de abuso.' },
    { title: '8. Compartilhamento de dados', text: 'Não vendemos seus dados pessoais. Podemos usar serviços de infraestrutura, autenticação, banco de dados, armazenamento, notificações, anúncios, pagamentos e moderação. Informações também podem ser compartilhadas quando exigido por lei ou para proteger usuários e a plataforma.' },
    { title: '9. Premium e anúncios', text: 'Alguns recursos podem depender de anúncios ou assinatura Premium. Assinaturas, cobranças, cancelamentos e reembolsos seguem as regras da loja ou do meio de pagamento utilizado.' },
    { title: '10. Exclusão de conta', text: 'Você pode excluir sua conta na área de segurança. A exclusão remove perfil, fotos, localização, curtidas, matches, mensagens e chats quando tecnicamente possível. Registros mínimos podem ser mantidos temporariamente por obrigação legal, segurança ou prevenção de abuso.' },
    { title: '11. Segurança infantil', text: 'O Raddo não permite menores de 18 anos. Exploração, abuso ou sexualização de menores é proibida e pode ser denunciada às autoridades competentes.' },
    { title: '12. Alterações', text: 'Estes termos podem ser atualizados para refletir mudanças no app, exigências legais ou melhorias de segurança. O uso contínuo após alterações indica concordância com a versão atualizada.' },
    { title: '13. Contato', text: 'Para dúvidas, denúncias, privacidade ou exclusão de dados, use o canal de suporte informado na página do app ou nos materiais oficiais do Raddo.' },
  ],
  'en-US': [
    { title: '1. Using Raddo', text: 'Raddo is a social app for meeting nearby people, messaging matches, and joining local map chats. By using it, you agree to respect others and not publish illegal, offensive, fraudulent, discriminatory, violent, rights-infringing, or sexual content involving minors.' },
    { title: '2. Minimum age', text: 'Raddo is only for people aged 18 or older. Accounts suspected of belonging to minors may be removed or banned without prior notice.' },
    { title: '3. Location', text: 'The app uses your location to calculate distance, show nearby chats, and improve discovery. Your photo appears on the map only when you enable that option, which can be disabled in safety settings.' },
    { title: '4. Profile, photos, and messages', text: 'You are responsible for the information, photos, messages, and chats you publish. Profile photos, chat covers, and uploaded images may undergo automated checks and human review when needed to protect the community.' },
    { title: '5. Prohibited content', text: 'Explicit nudity, sexual exploitation, content involving minors, harassment, threats, hate speech, scams, spam, improper disclosure of personal data, extreme violence, and illegal material are prohibited.' },
    { title: '6. Reports, blocks, and moderation', text: 'Users may report inappropriate profiles, chats, and content. Raddo may review reports, remove content, limit features, block chat access, or ban accounts. Chat owners and moderators may also remove messages and participants.' },
    { title: '7. Privacy and data', text: 'We collect data needed to operate the app, such as profile details, photos, preferences, location when enabled, likes, matches, messages, reports, blocks, notification tokens, and technical records. It is used for authentication, discovery, chat, safety, and abuse prevention.' },
    { title: '8. Data sharing', text: 'We do not sell personal data. We may use infrastructure, authentication, database, storage, notification, advertising, payment, and moderation providers. Information may also be shared when required by law or to protect users and the platform.' },
    { title: '9. Premium and ads', text: 'Some features may depend on ads or a Premium subscription. Subscriptions, charges, cancellations, and refunds follow the rules of the store or payment method used.' },
    { title: '10. Account deletion', text: 'You can delete your account in the safety area. Where technically possible, deletion removes your profile, photos, location, likes, matches, messages, and chats. Minimal records may be kept temporarily for legal, safety, or abuse-prevention reasons.' },
    { title: '11. Child safety', text: 'Raddo does not allow anyone under 18. Exploitation, abuse, or sexualization of minors is prohibited and may be reported to the appropriate authorities.' },
    { title: '12. Changes', text: 'These terms may be updated to reflect app changes, legal requirements, or safety improvements. Continued use after a change means acceptance of the updated version.' },
    { title: '13. Contact', text: 'For questions, reports, privacy, or data deletion, use the support channel listed on the app page or in official Raddo materials.' },
  ],
  es: [
    { title: '1. Uso de Raddo', text: 'Raddo es una app social para conocer personas cercanas, conversar con matches y participar en chats locales del mapa. Al usarla, aceptas respetar a los demás y no publicar contenido ilegal, ofensivo, fraudulento, discriminatorio, violento, que infrinja derechos o contenido sexual con menores.' },
    { title: '2. Edad mínima', text: 'Raddo es solo para mayores de 18 años. Las cuentas que parezcan pertenecer a menores pueden ser eliminadas o bloqueadas sin aviso previo.' },
    { title: '3. Ubicación', text: 'La app usa tu ubicación para calcular distancias, mostrar chats cercanos y mejorar el descubrimiento. Tu foto solo aparece en el mapa cuando activas esa opción, que puedes desactivar en seguridad.' },
    { title: '4. Perfil, fotos y mensajes', text: 'Eres responsable de la información, fotos, mensajes y chats que publicas. Las fotos de perfil, portadas e imágenes pueden pasar por verificaciones automáticas y revisión humana para proteger a la comunidad.' },
    { title: '5. Contenido prohibido', text: 'Se prohíbe la desnudez explícita, explotación sexual, contenido con menores, acoso, amenazas, odio, estafas, spam, divulgación indebida de datos personales, violencia extrema y cualquier material ilegal.' },
    { title: '6. Denuncias, bloqueos y moderación', text: 'Los usuarios pueden denunciar perfiles, chats y contenido. Raddo puede revisar denuncias, eliminar contenido, limitar funciones, bloquear chats o banear cuentas. Los propietarios y moderadores también pueden eliminar mensajes y participantes.' },
    { title: '7. Privacidad y datos', text: 'Recopilamos datos necesarios para operar la app, como perfil, fotos, preferencias, ubicación cuando está activa, likes, matches, mensajes, denuncias, bloqueos, tokens de notificación y registros técnicos. Se usan para autenticación, descubrimiento, chat, seguridad y prevención de abusos.' },
    { title: '8. Compartir datos', text: 'No vendemos tus datos personales. Podemos usar servicios de infraestructura, autenticación, base de datos, almacenamiento, notificaciones, anuncios, pagos y moderación. También podemos compartir información por obligación legal o para proteger a usuarios y la plataforma.' },
    { title: '9. Premium y anuncios', text: 'Algunas funciones pueden depender de anuncios o de Premium. Las suscripciones, cobros, cancelaciones y reembolsos siguen las reglas de la tienda o medio de pago utilizado.' },
    { title: '10. Eliminación de cuenta', text: 'Puedes eliminar tu cuenta en seguridad. Cuando sea técnicamente posible, se eliminan perfil, fotos, ubicación, likes, matches, mensajes y chats. Algunos registros mínimos pueden conservarse temporalmente por motivos legales, de seguridad o prevención de abusos.' },
    { title: '11. Seguridad infantil', text: 'Raddo no permite menores de 18 años. La explotación, abuso o sexualización de menores está prohibida y puede denunciarse a las autoridades competentes.' },
    { title: '12. Cambios', text: 'Estos términos pueden actualizarse por cambios en la app, requisitos legales o mejoras de seguridad. Seguir usando Raddo implica aceptar la versión actualizada.' },
    { title: '13. Contacto', text: 'Para consultas, denuncias, privacidad o eliminación de datos, usa el canal de soporte indicado en la página de la app o en los materiales oficiales de Raddo.' },
  ],
  'zh-CN': [
    { title: '1. 使用 Raddo', text: 'Raddo 是用于认识附近的人、与匹配对象聊天及加入地图本地聊天的社交应用。使用本应用即表示你同意尊重他人，不发布违法、冒犯、欺诈、歧视、暴力、侵犯他人权利或涉及未成年人的色情内容。' },
    { title: '2. 最低年龄', text: 'Raddo 仅供年满 18 岁的人使用。疑似属于未成年人的账户可能会在不事先通知的情况下被删除或封禁。' },
    { title: '3. 位置', text: '应用使用你的位置计算距离、显示附近聊天并改善推荐。只有在你主动启用时，照片才会显示在地图上；你可在安全设置中关闭此功能。' },
    { title: '4. 资料、照片和消息', text: '你应对发布的资料、照片、消息和聊天负责。为保护社区，头像、聊天封面及上传的图片可能接受自动检查和必要的人工审核。' },
    { title: '5. 禁止内容', text: '禁止发布露骨裸体、性剥削、涉及未成年人的内容、骚扰、威胁、仇恨言论、诈骗、垃圾信息、不当披露个人数据、极端暴力及任何非法材料。' },
    { title: '6. 举报、屏蔽和审核', text: '用户可以举报不当资料、聊天和内容。Raddo 可审核举报、删除内容、限制功能、禁止进入聊天或封禁账户。聊天创建者和管理员也可以删除消息和参与者。' },
    { title: '7. 隐私和数据', text: '我们收集应用运行所需的数据，例如资料、照片、偏好、启用时的位置、点赞、匹配、消息、举报、屏蔽、通知令牌和技术记录。这些数据用于身份验证、推荐、聊天、安全和防止滥用。' },
    { title: '8. 数据共享', text: '我们不会出售个人数据。我们可能使用基础设施、身份验证、数据库、存储、通知、广告、支付和审核服务。法律要求或保护用户及平台时也可能共享信息。' },
    { title: '9. 高级版和广告', text: '部分功能可能依赖广告或高级版订阅。订阅、收费、取消和退款遵循所用商店或支付方式的规则。' },
    { title: '10. 删除账户', text: '你可以在安全区域删除账户。在技术可行的情况下，资料、照片、位置、点赞、匹配、消息和聊天将被删除。出于法律、安全或防止滥用的原因，少量记录可能暂时保留。' },
    { title: '11. 儿童安全', text: 'Raddo 不允许 18 岁以下人士使用。严禁剥削、虐待或色情化未成年人，相关行为可能被报告给主管机关。' },
    { title: '12. 条款变更', text: '这些条款可能因应用变化、法律要求或安全改进而更新。更新后继续使用即表示接受新版本。' },
    { title: '13. 联系方式', text: '如需咨询、举报、处理隐私或删除数据，请使用应用页面或 Raddo 官方材料中提供的支持渠道。' },
  ],
  'hi-IN': [
    { title: '1. Raddo का उपयोग', text: 'Raddo पास के लोगों से मिलने, मैच से बात करने और मैप की स्थानीय चैट में शामिल होने वाला सामाजिक ऐप है। इसका उपयोग करके आप दूसरों का सम्मान करने और गैरकानूनी, अपमानजनक, धोखाधड़ी, भेदभावपूर्ण, हिंसक, अधिकारों का उल्लंघन करने वाली या नाबालिगों से जुड़ी यौन सामग्री प्रकाशित न करने पर सहमत होते हैं।' },
    { title: '2. न्यूनतम आयु', text: 'Raddo केवल 18 वर्ष या उससे अधिक आयु के लोगों के लिए है। नाबालिगों के खाते बिना पूर्व सूचना हटाए या प्रतिबंधित किए जा सकते हैं।' },
    { title: '3. स्थान', text: 'ऐप दूरी की गणना, पास की चैट दिखाने और खोज बेहतर करने के लिए स्थान का उपयोग करता है। आपकी फ़ोटो केवल विकल्प चालू करने पर मैप पर दिखती है; इसे सुरक्षा सेटिंग में बंद किया जा सकता है।' },
    { title: '4. प्रोफ़ाइल, फ़ोटो और संदेश', text: 'आप अपनी प्रकाशित जानकारी, फ़ोटो, संदेश और चैट के लिए ज़िम्मेदार हैं। समुदाय की सुरक्षा के लिए प्रोफ़ाइल फ़ोटो, चैट कवर और अपलोड की गई तस्वीरों की स्वचालित जाँच और आवश्यक मानव समीक्षा हो सकती है।' },
    { title: '5. प्रतिबंधित सामग्री', text: 'स्पष्ट नग्नता, यौन शोषण, नाबालिगों से जुड़ी सामग्री, उत्पीड़न, धमकी, घृणा, धोखाधड़ी, स्पैम, व्यक्तिगत डेटा का अनुचित खुलासा, अत्यधिक हिंसा और गैरकानूनी सामग्री प्रतिबंधित है।' },
    { title: '6. रिपोर्ट, ब्लॉक और मॉडरेशन', text: 'उपयोगकर्ता अनुचित प्रोफ़ाइल, चैट और सामग्री रिपोर्ट कर सकते हैं। Raddo रिपोर्ट की समीक्षा, सामग्री हटाने, सुविधाएँ सीमित करने, चैट रोकने या खाते प्रतिबंधित करने का अधिकार रखता है। चैट मालिक और मॉडरेटर संदेश और प्रतिभागी भी हटा सकते हैं।' },
    { title: '7. गोपनीयता और डेटा', text: 'हम ऐप चलाने के लिए आवश्यक डेटा एकत्र करते हैं, जैसे प्रोफ़ाइल, फ़ोटो, पसंद, चालू होने पर स्थान, लाइक, मैच, संदेश, रिपोर्ट, ब्लॉक, सूचना टोकन और तकनीकी रिकॉर्ड। इनका उपयोग प्रमाणीकरण, खोज, चैट, सुरक्षा और दुरुपयोग रोकने के लिए होता है।' },
    { title: '8. डेटा साझा करना', text: 'हम व्यक्तिगत डेटा नहीं बेचते। हम इन्फ्रास्ट्रक्चर, प्रमाणीकरण, डेटाबेस, स्टोरेज, सूचना, विज्ञापन, भुगतान और मॉडरेशन सेवाओं का उपयोग कर सकते हैं। कानून की माँग या उपयोगकर्ताओं और प्लेटफ़ॉर्म की सुरक्षा के लिए जानकारी साझा की जा सकती है।' },
    { title: '9. प्रीमियम और विज्ञापन', text: 'कुछ सुविधाएँ विज्ञापन या प्रीमियम सदस्यता पर निर्भर हो सकती हैं। सदस्यता, शुल्क, रद्दीकरण और रिफंड उपयोग किए गए स्टोर या भुगतान माध्यम के नियमों के अनुसार होते हैं।' },
    { title: '10. खाता हटाना', text: 'आप सुरक्षा क्षेत्र में खाता हटा सकते हैं। तकनीकी रूप से संभव होने पर प्रोफ़ाइल, फ़ोटो, स्थान, लाइक, मैच, संदेश और चैट हटाए जाते हैं। कानूनी, सुरक्षा या दुरुपयोग रोकने के कारण न्यूनतम रिकॉर्ड अस्थायी रूप से रखे जा सकते हैं।' },
    { title: '11. बाल सुरक्षा', text: 'Raddo पर 18 वर्ष से कम आयु के लोग अनुमत नहीं हैं। नाबालिगों का शोषण, दुर्व्यवहार या यौन चित्रण प्रतिबंधित है और संबंधित अधिकारियों को रिपोर्ट किया जा सकता है।' },
    { title: '12. बदलाव', text: 'ऐप के बदलाव, कानूनी आवश्यकताओं या सुरक्षा सुधारों के अनुसार ये शर्तें अपडेट हो सकती हैं। बदलाव के बाद लगातार उपयोग का अर्थ अपडेट संस्करण को स्वीकार करना है।' },
    { title: '13. संपर्क', text: 'प्रश्न, रिपोर्ट, गोपनीयता या डेटा हटाने के लिए ऐप पेज या Raddo की आधिकारिक सामग्री में दिए सहायता चैनल का उपयोग करें।' },
  ],
};
